### ISSUE TITLE
Documentation clarity

### ISSUE THREAD

**Issue by iamjli** [pyranges/pyranges#151]
The documentation is pretty difficult to read since all pyranges attributes and methods listed are alphabetically and takes a while to scroll through. I do think this could turn away some potential users as well. 

Off the top of my head, one way to organize methods could be as follows: 

- I/O & conversion to/from other python objects 
- operations with other pyranges objects (i.e. join, intersect)
- self genomic manipulations (i.e. window, merge)
- others

**Comment by endrebak** [comment]
That is what was in the original docs, but I switched to AutoAPI to automatically generate docs. 

I should look at how to split the docs.

(Note to self) docs here: https://github.com/readthedocs/sphinx-autoapi

**Comment by marco-mariotti** [comment]
New documentation available at https://pyranges.readthedocs.io/
