### ISSUE TITLE
[Feature request] Publish prebuilt wheels

### ISSUE THREAD

**Issue by jwarwick-delfi** [pyranges/pyranges#256]
As this project matures, it would be nice to publish prebuilt wheels both for ease of use and to enable consumers who need a wheel instead of a sdist, as is my situation. I'm using a build system that uses pex and pip to create distributions for various architectures, and one of the requirements is that a wheel (not sdist) be available for all packages on each architecture. Unfortunately, at the moment that means I can't use pyranges in my project.

There is a nice [github actions extension for building wheels on multiple archs and versions](https://github.com/pypa/cibuildwheel) - here is an [example of it in use](https://github.com/tornadoweb/tornado/blob/master/.github/workflows/build.yml). However it looks like you're using Travis CI, I apologize that I am not familiar with that system.

A good starting point might be wheels for:
* OSX on aarch64
* manylinux2014 on aarch64 and x86_64
* Cpython 3.7, 3.8, 3.9, 3.10

**Comment by endrebak** [comment]
I'm switching to github actions, have done so already for many things.

Would you be interested in making a pull request? I'd help out and submit it eventually :)

**Comment by endrebak** [comment]
I dunno why github (gmail?) did not notify me about your post btw, sorry for the late reply.

**Comment by endrebak** [comment]
[Guide to pushing wheels from C/I](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)

[Introduction to wheels from realpython.com](https://realpython.com/python-wheels/)

**Comment by endrebak** [comment]
Bamread is currently pushing loads of nice wheels with its action: https://pypi.org/project/bamread/#files

Will update the other repos to use it.

**Comment by endrebak** [comment]
Fixed.
