### ISSUE TITLE
Importing pyranges 

### ISSUE THREAD

**Issue by Sayyam-Shah** [pyranges/pyranges#277]
Hello @endrebak

I installed pyranges using pip install pyranges --user.
Requirement already satisfied: six>=1.5 in /cluster/tools/software/centos7/python/3.7.2/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->pyranges) (1.12.0)
Installing collected packages: pyranges
Successfully installed pyranges-0.0.117

However, when I call on it using import pyranges as pr, I get the below error.
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyranges'

May you please help me debug this? I am using an HPC cluster.

**Comment by endrebak** [comment]
Try `which python` to see if it is the one you expect: /cluster/tools/software/centos7/python/3.7.2/lib/python3.7/site-packages
