### ISSUE TITLE
pyranges could not be installed on Python 3.11 due to pyrle dependency failed.

### ISSUE THREAD

**Issue by y9c** [pyranges/pyranges#283]
https://github.com/pyranges/pyrle/issues/6

**Comment by Rohan-cod** [comment]
@endrebak can you please check? We are also facing this issue

**Comment by deusdevok** [comment]
I am still facing this issue as well

**Comment by endrebak** [comment]
I will check and try to fix it tomorrow.

Perhaps it should not be a strict dependency.

Endre

**Comment by endrebak** [comment]
I've removed the pyrle dependency in 0.0.124. Does it work for you?

**Comment by endrebak** [comment]
Now pyrle should work on python3.11 too.

**Comment by kyleabeauchamp** [comment]
FYI it seems that bioconda users are still is stuck on 3.10 due to these issues.

**Comment by endrebak** [comment]
Thanks for notifying me.

Do you have more info, like why you think it is the same issue?

**Comment by kyleabeauchamp** [comment]
Yep.  The latest version of pyrle is available on bioconda (https://anaconda.org/bioconda/pyrle/files), but only has builds available for python up to version 3.10 (no 3.11).  Thus pyrle + pyranges still cannot be installed via bioconda on python 3.11.
