### ISSUE TITLE
Feature request: wrap panda dataframe methods

### ISSUE THREAD

**Issue by marco-mariotti** [pyranges/pyranges#286]
Working with PyRanges, I very often have to transform back and forth to pandas DataFrame.
It's always because I need the same methods: DataFrame.groupby and DataFrame.apply.

Could you make these methods available directly in pyranges.PyRanges? I guess they could be easily implemented, with the only minor inconsistency that groups must be within each chromosome group.

**Comment by endrebak** [comment]
I have considered this. I’ll look into it.

Endre

**Comment by endrebak** [comment]
You could do

```
gr.apply(lambda df: df.groupby(args))

gr.apply(groupby_function)
```

Is this good enough?

I think adding `groupby` might lead to many weird corner cases where there is a mismatch between pandas and pyranges. Furthermore, we'd might get lots more support questions since then it would be our function.

Perhaps it is best to add examples to the book?

**Comment by marco-mariotti** [comment]
OK, let's turn this into a enhancement request for the book: a chapter on Pyranges / Pandas interaction.
There's a minimal example in the tutorial now
