### ISSUE TITLE
Row-order after df1.join(df2, how="right")

### ISSUE THREAD

**Issue by aallahyar** [pyranges/pyranges#303]
**Disclaimer:**
This is not an issue or bug, just an observation. 
If correct, I propose to add a bit of text in the documentation to clarify the matter.

**What:**
I was using `.join()` and noticed that the order of elements in `self` may change when using `how="right"` or `how="left"`. This is even visible in [the provided example](https://pyranges.readthedocs.io/en/latest/autoapi/pyranges/index.html#pyranges.PyRanges.join) of `.join()` method where `how="right"` is used. For example, in case we use:
```python
f1 = pr.from_dict({'Chromosome': ['chr1', 'chr1', 'chr1'], 'Start': [3, 8, 5],
                   'End': [6, 9, 7], 'Name': ['interval1', 'interval3', 'interval2']})
f2 = pr.from_dict({'Chromosome': ['chr1', 'chr1'], 'Start': [1, 6],
                   'End': [2, 7], 'Name': ['a', 'b']})

print(f1)
print(f1.join(f2, how="left"))
```
we will see
```
+--------------+-----------+-----------+------------+
| Chromosome   |     Start |       End | Name       |
| (category)   |   (int32) |   (int32) | (object)   |
|--------------+-----------+-----------+------------|
| chr1         |         3 |         6 | interval1  |
| chr1         |         8 |         9 | interval3  |
| chr1         |         5 |         7 | interval2  |
+--------------+-----------+-----------+------------+
Unstranded PyRanges object has 3 rows and 4 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
+--------------+-----------+-----------+------------+-----------+-------+
| Chromosome   |     Start |       End | Name       |   Start_b | +2    |
| (category)   |   (int64) |   (int64) | (object)   |   (int64) | ...   |
|--------------+-----------+-----------+------------+-----------+-------|
| chr1         |         5 |         7 | interval2  |         6 | ...   |
| chr1         |         3 |         6 | interval1  |        -1 | ...   |
| chr1         |         8 |         9 | interval3  |        -1 | ...   |
+--------------+-----------+-----------+------------+-----------+-------+
Unstranded PyRanges object has 3 rows and 7 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
2 hidden columns: End_b, Name_b
``` 

Notice that the order of rows in `f1` is no longer the same.
I understand that this is most likely a "design choice" considering that `interval1` and `interval3` are not overlapping with any interval in `f2`. Regardless, I think it makes sense to add a few sentences in the documentation and emphasize that the order is not preserved after `join()`.
If this is not a "design choice", I wonder if preserving the order is a "useful" feature?
In case of the former, I would be happy to provide this as a pull request if my reasoning is agreed by the developer(s).

**Comment by endrebak** [comment]
It would not be hard to preserve the ordering. Perhaps it could be done with a keyword flag?

I have some days in May where I have the time to fix this btw. I can do it, but in a few weeks.

**Comment by aallahyar** [comment]
Thank for your remark @endrebak.
Happy to see that you agree with the utility of this functionality.

I took the liberty of implementing a suggested pr, you may see it in #304. 
Hope you like it.

I also added a bit of documentation to reflect this change.

Thanks for PyRange, its fun/fast to work with it!

**Comment by endrebak** [comment]
Merged into master branch. Thanks for contributing and reporting :D
