### ISSUE TITLE
Documentation is unaccessible

### ISSUE THREAD

**Issue by DongzeHE** [pyranges/pyranges#311]
Hello, the site https://biocore-ntnu.github.io/pyranges/ returns 404.

**Comment by marco-mariotti** [comment]
Thanks, we recently changed address but haven't updated the link.
Use this: https://pyranges.github.io/pyranges/

BTW, you can also check this preview of the new pyranges documentation, including an extensive tutorial:
https://docs.google.com/document/d/1NqSRuCvJ2ifPoOgLqtCAmnu2D3vGBg2M9tarnH7qFXE/edit?usp=sharing

It will soon be added to the above link too.

**Comment by endrebak** [comment]
I will have a look later today

**Comment by endrebak** [comment]
This was fixed. Thanks for reporting.
