### ISSUE TITLE
Streamline README.md

### ISSUE THREAD

**Issue by marco-mariotti** [pyranges/pyranges#313]
With the new tutorial, it most convenient that the README is minimal and contains no code.
Structure:
- Brief description of pyranges scope and features. Include links to benchmark to support claim of speed and memory efficiency
- installation
- description of documentation structure and links to each part
- citation
- supporting pyranges
- asking for help

**Comment by endrebak** [comment]
I agree. It is out of date. And we should make new efficiency graphs. 

And link to projects and discussions so others can see what we are working on.

I should write developer docs, but this is preferable to do after we fix C/I, tox, etc. so the flow is streamlined.

**Comment by endrebak** [comment]
We should also remove out of date badges and add new ones when we get C/I up and running.

Feel free to make a PR.

**Comment by marco-mariotti** [comment]
Done in https://github.com/pyranges/pyranges/pull/347
