### ISSUE TITLE
Write developer docs?

### ISSUE THREAD

**Issue by endrebak** [pyranges/pyranges#338]
Should include

- how to run the different testing and linting tools
- something like these pr/testing guidelines: https://snakemake.readthedocs.io/en/stable/project_info/contributing.html#pull-request-guidelines
- how to run the C/I locally with https://github.com/nektos/act
- how to write documentation and docstrings

What else?

Bumping and changelogs would be nice to have automated in C/I too

**Comment by marco-mariotti** [comment]
Done in https://github.com/pyranges/pyranges/pull/347
See https://pyranges.readthedocs.io/en/latest/developer_guide.html
