### ISSUE TITLE
pandas futurewarning in init.py

### ISSUE THREAD

**Issue by Jeltje** [pyranges/pyranges#349]
I pip installed pyranges inside conda and got the following error when reading in a bed file like so
`gr = pr.read_bed('chr22.bed')`:
`
C:\Users\yinna\anaconda3\envs\r4-base\Lib\site-packages\pyranges\methods\init.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return {k: v for k, v in df.groupby(grpby_key)}
`
pandas                2.1.1
pyranges              0.0.129

And indeed, changing the code to  
`{k: v for k, v in df.groupby(grpby_key, observed=False)}`
fixes the warning.

**Comment by marco-mariotti** [comment]
Fixed in https://github.com/pyranges/pyranges/pull/347
