### ISSUE TITLE
Return overlap between PyRanges objects, keeping columns from both?

### ISSUE THREAD

**Issue by BeyondTheProof** [pyranges/pyranges#355]
I am trying to implement a method to fetch and potentially summarize information from genomic intervals. For example, given a set of CpG sites with methylation (beta) values between 0 and 1, find the mean beta value for some windows of size 2Mb.

Ideally, this would be extensible in that I could return the individual CpG site methylation levels (along with their IDs) for each such window. 

This can be simulated with the `chipseq` data implemented in pyranges:

```
import pyranges as pr
import pandas as pd

# Pretend the chip-seq data is actually methylation, with `Score` as the beta value
signal_data = pr.data.chipseq()
```

Taking a single 2MB region using PyRanges:
```
# Fetch a region using PyRanges
%timeit signal_data['chr1', 1_000_000:3_000_000].Score.sum()
```
Returns `10.2 ms ± 1.52 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)`.

Doing this with Pandas is much faster:
```
# Fetch a region using Pandas
signal_data_df = signal_data.df

%timeit signal_data_df[(signal_data_df["Chromosome"] == "chr1") & (signal_data_df["Start"] < 3_000_000) & (signal_data_df["End"] > 1_000_000)].Score.sum()
```
Returns `804 µs ± 9.45 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)`.

So maybe PyRanges is not optimized for single-region operations. Indeed, I see there's some discussion about this, maybe [this](https://github.com/pyranges/pyranges/issues/165) is relevant. So if I try to overlap two PyRanges objects, it indeeds seems quite fast:

```
num_regions = 100
window_size = 2_000_000
query_regions = pr.PyRanges(
    pd.DataFrame(
        {
            "Chromosome": ["chr1" for ii in range(num_regions)],
            "Start": [ii * window_size for ii in range(num_regions)],
            "End": [(ii+1) * window_size for ii in range(num_regions)],
            "ID": [ii for ii in range(num_regions)],
        }
    )
)

%timeit signal_data.intersect(query_regions)
```

This gives us `35.9 ms ± 585 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)`, which is only 3.5 times longer than for a single region, despite this being 100 regions. From playing around, it looks about constant time (awesome!).

However, I can't figure out how, if at all possible, to either *group by* region in `query_regions`, or to retain the columns in `query_regions` to group on the ID there. Doing `query_regions.intersect(signal_data)` runs into a similar problem -- all the information from `signal_data` are lost. 

Is there a way around this here problem, or should I seek alternative avenues?

**Comment by BeyondTheProof** [comment]
Note: one alternative I could use, although it would require more coding, is pyBedTools. Unfortunately, in the past, I've had to deal with lots of temporary files and the such to get it to work nicely.

**Comment by marco-mariotti** [comment]
This is an interesting problem for which we should add support. In general, methods that accept a "other" PyRanges shrink it to the minimum because its information may not align to the "self" one... for example, there may be a correspondance between multiple rows in "other" and a single one in self. So it isn't obvious how to keep any such metadata columns.

So, note to dev team: add support to optional argument agg (such as https://pyranges.readthedocs.io/en/latest/autoapi/pyranges/index.html#pyranges.PyRanges.boundaries) to provide a way to maintain metadata columns in methods including intersect.

I can't think of a good workaround while we work this out... So I'll propose a bad one:
Stack the query regions and the signal data into single PyRanges object; beforehand, define some attribute to distinguish the interval source (x.wherefrom='query' or x.wherefrom='signal'). Also, define some unique ID per query.
Use pyranges.cluster to effectively have grouping IDs for each row, which will correspond to the query regions. Now you can throw away query rows, then do:  groupby('cluster').Score.sum()

BUT: it works only if the query regions are non-overlapping; and each signal should map to only one query region. If not, clusters will merge two query regions. You can test whether this happens by running pandas value_counts  for (cluster, queryID) in query rows only. If anything is counted more than once, ... well, ouch.

**Comment by BeyondTheProof** [comment]
Interesting solution. I will try to do that! 

Overlapping intervals can definitely happen in my use case. A possible solution that problem can be to split intervals where they overlap into sub-intervals, so if A overlaps B, split into A \ B, A ∩ B, and B \ A, then follow the procedure you mentioned.

I'll check periodically on this. Let me know if there's anything I can do to help, although be warned that I don't know the PyRanges code!

**Comment by endrebak** [comment]
Join does what you want I think. On vacation, will read more thoroughly later.

**Comment by endrebak** [comment]
We also have tile or something similar which creates window of custom size.

If you have an example of inputs and desired outputs I can help :D

**Comment by marco-mariotti** [comment]
Endre's solution is the right one. I'll extend it here:


```
signal_data = pr.data.chipseq()

# make up some ints, or it's all zeros, not great as example
signal_data.Score = np.random.randint(0, 100, len(signal_data))
signal_data

+--------------+-----------+-----------+-----------+-----------+-----------+------------+-----------+--------------+
| Chromosome   | Start     | End       | ID        | Start_b   | End_b     | Name       | Score     | Strand       |
| (category)   | (int32)   | (int32)   | (int64)   | (int32)   | (int32)   | (object)   | (int64)   | (category)   |
|--------------+-----------+-----------+-----------+-----------+-----------+------------+-----------+--------------|
| chr1         | 0         | 2000000   | 0         | 1541598   | 1541623   | U0         | 42        | +            |
| chr1         | 0         | 2000000   | 0         | 1599121   | 1599146   | U0         | 5         | +            |
| chr1         | 2000000   | 4000000   | 1         | 3504032   | 3504057   | U0         | 26        | +            |
| chr1         | 2000000   | 4000000   | 1         | 3806532   | 3806557   | U0         | 58        | +            |
| ...          | ...       | ...       | ...       | ...       | ...       | ...        | ...       | ...          |
| chr1         | 198000000 | 200000000 | 99        | 198766801 | 198766826 | U0         | 72        | -            |
| chr1         | 198000000 | 200000000 | 99        | 198768059 | 198768084 | U0         | 35        | -            |
| chr1         | 198000000 | 200000000 | 99        | 199073823 | 199073848 | U0         | 39        | -            |
| chr1         | 198000000 | 200000000 | 99        | 199098617 | 199098642 | U0         | 68        | -            |
+--------------+-----------+-----------+-----------+-----------+-----------+------------+-----------+--------------+
Stranded PyRanges object has 706 rows and 9 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
```

This is does the trick:

```
j=query_regions.join(signal_data)
j

+--------------+-----------+-----------+-----------+-----------+-----------+------------+-----------+--------------+
| Chromosome   | Start     | End       | ID        | Start_b   | End_b     | Name       | Score     | Strand       |
| (category)   | (int32)   | (int32)   | (int64)   | (int32)   | (int32)   | (object)   | (int64)   | (category)   |
|--------------+-----------+-----------+-----------+-----------+-----------+------------+-----------+--------------|
| chr1         | 0         | 2000000   | 0         | 1541598   | 1541623   | U0         | 0         | +            |
| chr1         | 0         | 2000000   | 0         | 1599121   | 1599146   | U0         | 0         | +            |
| chr1         | 2000000   | 4000000   | 1         | 3504032   | 3504057   | U0         | 0         | +            |
| chr1         | 2000000   | 4000000   | 1         | 3806532   | 3806557   | U0         | 0         | +            |
| ...          | ...       | ...       | ...       | ...       | ...       | ...        | ...       | ...          |
| chr1         | 198000000 | 200000000 | 99        | 198766801 | 198766826 | U0         | 0         | -            |
| chr1         | 198000000 | 200000000 | 99        | 198768059 | 198768084 | U0         | 0         | -            |
| chr1         | 198000000 | 200000000 | 99        | 199073823 | 199073848 | U0         | 0         | -            |
| chr1         | 198000000 | 200000000 | 99        | 199098617 | 199098642 | U0         | 0         | -            |
+--------------+-----------+-----------+-----------+-----------+-----------+------------+-----------+--------------+
Stranded PyRanges object has 706 rows and 9 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
```


Now you can groupby ID and aggregate however you like, e.g.

```
j.df.groupby('ID').Score.sum()
ID
0     151
1     384
2     560
3     239
4     243
     ...
95    523
96    298
97    326
98    494
99    434
Name: Score, Length: 89, dtype: int64

```
