### ISSUE TITLE
when using .coverage: AttributeError: module 'numpy' has no attribute 'long'

### ISSUE THREAD

**Issue by brian-arnold** [pyranges/pyranges#360]
I mamba installed pyranges in a fresh environment, and it defaults to installing numpy version 1.26. When I use the coverage function, I get the following error:

"AttributeError: module 'numpy' has no attribute 'long'"

which is an attribute that was [removed](https://stackoverflow.com/questions/76389395/attributeerror-module-numpy-has-no-attribute-long#:~:text=8-,Sadly,-%2C%20numpy.long) in numpy version 1.24?

Indeed, I was able bypass the error by making a new mamba environment with numpy= 1.23.5. Could this by chance be solved in the conda recipe?

Thanks for making this lovely software! It's suspiciously fast!
Brian

**Comment by marco-mariotti** [comment]
@maxtico can you have a look? seems like an easy fix. It was done already for other parts of the code but perhaps we didn't check all code. Look for all occurrences of np.long or numpy.long and update accordingly

If you do, update requirements.txt so that numpy minimum version will be 1.24
