### ISSUE TITLE
ModuleNotFoundError: No module named 'pyfaidx'

### ISSUE THREAD

**Issue by brian-arnold** [pyranges/pyranges#362]
encountered while using pr.get_sequence. Out of curiosity is there a particular reason this isn't installed with the other dependencies? mamba installing it fixed it.

**Comment by endrebak** [comment]
The less dependencies the better. The stuff that is used 1% of the time should not be a blocker for installing main pyranges :D

**Comment by brian-arnold** [comment]
fair enough!
