### ISSUE TITLE
pr.get_sequence may not be working?

### ISSUE THREAD

**Issue by brian-arnold** [pyranges/pyranges#366]
I'm following example commands from the documentation to get sequences from a fasta file (assembled genome) according to the intervals in a PyRanges object. Specifically I'm using the syntax:

seq = pr.get_sequence(gr, "temp.fasta") 

Manual inspection, the first time around, of the first few intervals from the first chromosome indicated it was getting the correct sequences. However, if I look at _any_ additional chromosome, it's clearly getting the incorrect sequence. I've manually inspected the FASTA file at a few interval coordinates and have also used `bedtools getfasta` command, which reports a different sequence than the PyRanges get_sequence function, and the bedtools sequence appears correct from manual inspection.

Other than a fasta file, are there any other specifications to use this function? Or is there perhaps something wrong with the function itself?

**Comment by marco-mariotti** [comment]
Hi,
get_sequence uses pyfaidx under the hood. What happens is that the fasta file is indexed if an index (.fai) is not found, then the index is used to fetch the requested sequence. One way in which things could go wrong is if you changed temp.fasta between uses of get_sequence, so that the .fai index is out of date. Try deleting the index and run again get_sequence

If this doesn't solve the issue, please provide data and example code to replicate it

**Comment by brian-arnold** [comment]
I deleted the index file and reran my notebook, and it appears a new index file was created in the same directory as the reference genome (NMEL.fasta). The first three sequences/entries for the first chromosome (NMEL_chr_1) seem to be the same as reported by bedtools, run by doing the following:

REF=Nmel.fasta
BED=kmers_test.txt # exported from PyRanges object
bedtools getfasta -fi ${REF} -bed ${BED} -fo ./bedtools_tmp.fa

However, when I start looking at other chromosomes, bedtools getfasta disagrees with PyRanges in terms of the sequence corresponding to that genomic interval, and manually inspecting the reference genome with VIM text editor suggests bedtools is right. The incorrect sequences PyRanges is grabbing appear to come from the provided reference genome, but are from other locations and on difference chromosomes.

Are there other ways to provide data to reproduce this? The most compressed version of the reference genome is 80MB but file sizes here are capped at 25MB. In your hands, with different data, do the sequences you pull out with PyRanges agree with bedtools fasta when you use a BED file and FASTA file that both contain multiple chromosomes?

Brian

**Comment by marco-mariotti** [comment]
In our hands, pyranges extracting sequences from annotations is correct. Our lab uses this function very often. Let's get to the bottom of this.

Please paste a link to the reference genome (hopefully you're working with public data?) and a few lines from the BED file, sufficient to reproduce the error. Also show the pyranges code you use to load the bed file and get sequences.

**Comment by marco-mariotti** [comment]
@brian-arnold can you provide data to replicate the error? Otherwise we'll have to close the issue
thanks!
