### ISSUE TITLE
pyranges.cluster() Exception: Starts/Ends not int64 or int32: int64 

### ISSUE THREAD

**Issue by mvolar** [pyranges/pyranges#371]
Hello,

im transitioning from R GenomicRanges into Python to streamline my reasearch work, however, im running into problems when im trying to run the cluster my ranges, the following excpetion gets thrown:

```
pyranges_obj.max_disjoint()
Exception: Starts/Ends not int64 or int32: int64
```

However i have made sure to coerce my columns into np.int64

```
df_pd["Start"] = np.int64(df_pd["Start"])
df_pd["End"] = np.int64(df_pd["End"])
pyranges_obj = pr.PyRanges(df_pd,int64=True)
```

And checking the type of the Start and end columns yieald numpy.int64 as result:

```
type(pyranges_obj.as_df()["Start"][0])==np.int64 // TRUE
type(pyranges_obj.as_df()["End"][0])==np.int64 // TRUE
```

**Comment by endrebak** [comment]
Thanks for reporting. And trying pyranges :)

Can you report your system and versions with pr.version_info()?

Do you have some example data where it happens?

**Comment by mvolar** [comment]
Hi, the version output is:

```
{'pyranges version': '0.0.129', 'pandas version': '2.0.3', 'numpy version': '1.25.1', 'python version': sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0), 'ncls': '0.0.68', 'sorted_nearest': '0.0.39', 'pyrle': 'not installed', 'ray': 'not installed', 'bamread': 'not installed', 'pyranges_db': 'not installed', 'pybigwig': 'not installed', 'hypothesis': 'not installed'}
```
The system is Windows 10, using interactive jupyter notebook.

Example minimal data which creates an error on my PC:

```
data = {'Chromosome': ['chr1', 'chr1', 'chr1'],
        'Start': [1, 4, 10],
        'End': [5, 8, 15]}

df = pd.DataFrame(data)

df["Start"] = np.int64(df["Start"])
df["End"] = np.int64(df["End"])
pyranges_obj = pr.PyRanges(df,int64=True)

pyranges_obj.cluster()
```

**Comment by endrebak** [comment]
We have no way of testing on windows, unfortunately.

I want to write the algorithms in rust instead of cython which should take care of such problems.

But I cannot help you for now, unfortunately.

**Comment by marco-mariotti** [comment]
Separate question: how are you running python in the first place? You can try WSL2 to run everything in a Linux like environment. Try a simple python interpreter at first. If this clears the error, you can Google how to run Jupiter from WSL2.
If you're already using WSL2... well, nevermind this comment

**Comment by endrebak** [comment]
There would be value in providing an alternative for Windows users.

I do not know why Windows does not treat/respect int64 like Linux/Mac does. I know that if you are unspecific about types int might interpret int or long differently, but it should not do so when one is being explicit.

**Comment by mvolar** [comment]
> Separate question: how are you running python in the first place? You can try WSL2 to run everything in a Linux like environment. Try a simple python interpreter at first. If this clears the error, you can Google how to run Jupiter from WSL2. If you're already using WSL2... well, nevermind this comment

Sorry for the wlong reply, had to write a polars extension for solution, avoiding pandas/pyranges. When running this code in WSL2 seems to work so the problem is in the cython/windows interface and their respective integer treatment.

**Comment by marco-mariotti** [comment]
Thanks mvolar. TL;DR for future readers: if you want pyranges in windows, use WSL2

**Comment by endrebak** [comment]
We should add this to the documentation! Thanks
