### ISSUE TITLE
`join` method exits unexpectedly

### ISSUE THREAD

**Issue by WhenMelancholy** [pyranges/pyranges#385]
I am using the join method of pyranger to merge two objects, with code like `fragments_in_regions = regions.join(fragments, nb_cpu=n_cpu)`. The regions object occupies about 30M of space, while the fragments object occupies about 12G. My server has 500G of memory. Using 20 CPUs causes the program to exit abruptly, and the Python interpreter does not output any information. Using 1 CPU, the line of code works well.

I suspect this is due to a memory issue. Is there a way to get more specific hints?

**Comment by endrebak** [comment]
The gpu arg should not be supported any more. What version are you using?

:)

**Comment by WhenMelancholy** [comment]
Hi @endrebak, I am using version 0.0.111, does this matters?

**Comment by endrebak** [comment]
The gpu arg is not supported. I'm doing minor revisions on my phd, but will look into this afterwards.

Ps. a new pyranges is out: https://github.com/pyranges/pyranges_1.x

**Comment by WhenMelancholy** [comment]
Thank you for your support! I will try use `nb_cpu=1` and investigate the pyranges 1.x later.
