### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'long'

### ISSUE THREAD

**Issue by xiucz** [pyranges/pyranges#392]
Hello, 
When I try to use `roi.set_intersect(whitelist_bed)` , it gives me error: AttributeError: module 'numpy' has no attribute 'long'

```{python}
>>> import numpy
>>> import pyranges
>>> print(numpy.__version__)
>>> 1.24.3

>>> import pyranges
>>> print(pyranges.__version__)
0.0.120
```
Can you tell me how to fix it ? Thanks a lot.
Best,
xiucz

**Comment by marco-mariotti** [comment]
please update pyranges to its latest version, this issue may have been already solved. Reopen the issue if not

**Comment by xiucz** [comment]
Hi, @marco-mariotti,  how to update now ? The lastest version on  conda or pip is 0.0.12 too.

![image](https://github.com/user-attachments/assets/8290003f-3ea6-4651-8886-fc1ee37c356a)
![image](https://github.com/user-attachments/assets/dab24c48-1474-4c36-b229-42c0ec5cfaae)
Best,
xiucz

**Comment by marco-mariotti** [comment]
The latest version is actually 0.1.2, as shown in your images. You update
with

pip install pyranges==0.1.2

Or the analogous conda command
Marco Mariotti
