### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by wdecoster** [pyranges/pyranges#44]
Hi,

If you are like me then you probably don't like writing documentation, or worse, keeping that documentation up to date. But your document is very helpful to get started with pyranges. It looks like I can clean up some nasty data-format-to-pandas parsers I wrote and replace them by pyranges code. Perhaps if I get more experienced with your module I can contribute (to the docs), but I'm not comfortable doing that yet.

After going through the documentation I have some questions/suggestions though:

1. I might have missed it, but I see you use `.slack()` and `slack=2` without explaining what that exactly this. It seems to extend intervals according to chapter 12 https://biocore-ntnu.github.io/pyranges/methods-for-manipulating-single-pyranges.html, but perhaps that needed to be specified earlier. It's first mentioned as a method in a code example in chapter 7
2. I think it would be very helpful if you could add drawings to the part about intersecting, overlapping and joining, like in the bedtools documentation (e.g. https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html). At least for me, it can initially be hard to wrap my head around how the intervals are combined. I like visualizations :)
3. Perhaps it would be useful to add some wikipedia links for background information, for example when you start talking about run-length encodings in part 20 (https://en.wikipedia.org/wiki/Run-length_encoding). Those concepts may not be obvious to everyone. But now I see the next part (21) is an introduction to RLEs, so maybe the order of the chapters needs to be revised. 

I could probably hack something together, but perhaps you can suggest an efficient solution for the following:
I have two data files, containing per genomic position some information. In addition to those, I have a bed file with intervals of interest.
Now for every interval in the bed file, I would like to slice the two data files, sum some numbers and statistically compare file A vs file B.
And then print some output, move on to the next interval.

Would it be most efficient to just iterate over the bed pyranges object and slice pyranges object of the data files? Or should I first annotate every record in the data files with the name of the interval in the bed file it belongs to?

Thanks,
Wouter

**Comment by endrebak** [comment]
2) and 3) are things I’d like to do eventually, but do not have time to do
now. :)

Keeping this open as a reminder and for other documentation discussions.

**Comment by wdecoster** [comment]
To elaborate on my question:  

1. I have two tsv files with "Chromosome", "Start", "End" and some numeric values per position (methylation frequencies to be specific, but that doesn't really matter I think).
I can easily make a PyRanges object out of those files.

1. I have a bed file delineating regulatory elements, for which I found pr.read_bed()

For every interval in the bed file I want to get all positions in both tsv files, and do some math on the numeric values (sum two columns per tsv and do a fisher exact test to compare both files).

**Comment by endrebak** [comment]
Would you mind if creating a proper question on bioinformatics stackexchange? I see that you have a user there :) ( If not, I can do it myself, if it is OK with you :) )

Setup for your q:

```
import pyranges as pr
import pandas as pd
import numpy as np

chromsizes = pr.PyRanges(pd.DataFrame({"Chromosome": [1, 2], "Start": [0, 0], "End": [int(1e5), int(5e4)]}))

cpg1 = pr.random(int(1e6), chromsizes=chromsizes)
cpg2 = pr.random(int(1e6), chromsizes=chromsizes)

cpg1.CPG = np.random.rand(int(1e6))
cpg2.CPG = np.random.rand(int(1e6))

regulatory_elements = pr.random(int(1e5), length=int(1e4), chromsizes=chromsizes)

cpg1
## +--------------+-----------+-----------+--------------+---------------------+
## | Chromosome   | Start     | End       | Strand       | CPG                 |
## | (category)   | (int32)   | (int32)   | (category)   | (float64)           |
## |--------------+-----------+-----------+--------------+---------------------|
## | 1            | 60747     | 60847     | +            | 0.7275817449530038  |
## | 1            | 56198     | 56298     | +            | 0.1391315979573874  |
## | 1            | 1559      | 1659      | +            | 0.6505381129224037  |
## | 1            | 23078     | 23178     | +            | 0.46810247651742276 |
## | ...          | ...       | ...       | ...          | ...                 |
## | 2            | 8784      | 8884      | -            | 0.5075106571553095  |
## | 2            | 45294     | 45394     | -            | 0.8109126084073928  |
## | 2            | 21060     | 21160     | -            | 0.9433211389481558  |
## | 2            | 3291      | 3391      | -            | 0.5173091813576819  |
## +--------------+-----------+-----------+--------------+---------------------+
## Stranded PyRanges object has 1,000,000 rows and 5 columns from 2 chromosomes.
## For printing, the PyRanges was sorted on Chromosome and Strand.

regulatory_elements
## +--------------+-----------+-----------+--------------+
## | Chromosome   | Start     | End       | Strand       |
## | (category)   | (int32)   | (int32)   | (category)   |
## |--------------+-----------+-----------+--------------|
## | 1            | 35873     | 45873     | +            |
## | 1            | 36132     | 46132     | +            |
## | 1            | 62380     | 72380     | +            |
## | 1            | 18864     | 28864     | +            |
## | ...          | ...       | ...       | ...          |
## | 2            | 20002     | 30002     | -            |
## | 2            | 21231     | 31231     | -            |
## | 2            | 25        | 10025     | -            |
## | 2            | 5249      | 15249     | -            |
## +--------------+-----------+-----------+--------------+
## Stranded PyRanges object has 100,000 rows and 4 columns from 2 chromosomes.
## For printing, the PyRanges was sorted on Chromosome and Strand.
```

**Comment by endrebak** [comment]
> For every interval in the bed file I want to get all positions in both tsv files, and do some math on the numeric values (sum two columns per tsv and do a fisher exact test to compare both files).

I guess you mean `I want to get all *overlapping* positions in both tsv files`?

**Comment by wdecoster** [comment]
I can write a SE question later today.

> I guess you mean I want to get all *overlapping* positions in both tsv files?

For a given bed interval I want to get all positions inside the interval (so yeah overlapping) for both files.

My current solution starts with a detour, as I don't actually use the bed object.

Something like this:
```
for chr, begin, end in pr.read_bed(args.bed).merge().as_df().itertuples(index=False, name=None):
    do_some_math(gr_tsv1[chr, begin:end].as_df()[[col1, col2]].sum(), gr_tsv2[chr, begin:end].as_df()[[col1, col2]].sum())
```

**Comment by endrebak** [comment]
It would be great if you could simulate some data that corresponds to your actual data. 

Thanks for bothering to do it! Then my answer will become helpful to a much wider range of people. I am guessing [rles](https://biocore-ntnu.github.io/pyranges/turning-ranges-into-rles.html) can be used to solve the problem quickly. I'll show you how :)

**Comment by endrebak** [comment]
You might get some inspiration here:

https://bioinformatics.stackexchange.com/questions/10654/summing-two-columns-where-they-share-interval-overlap/10655#10655

**Comment by wdecoster** [comment]
It took me a little longer than planned, but I wrote it as a question on SE and shared some example data: https://bioinformatics.stackexchange.com/questions/10679/efficiently-iterate-over-bed-and-subset-pyranges-objects

Thanks!
