### ISSUE TITLE
Chromosome bounds in slack

### ISSUE THREAD

**Issue by jnasser3** [pyranges/pyranges#82]
Hello,

A useful feature would be to be able to ensure that the slack function does not extend genomic ranges beyond the ends of chromosomes. This is implemented in bedtools: https://bedtools.readthedocs.io/en/latest/content/tools/slop.html

It seems there is some logic to prevent slack from creating negative positions (but maybe not for stranded slack), but there is no check for the other end of the chromosome.

I'm thinking this could be implemented as an optional argument to slack. If the optional 'bounds' object is passed, then the output of the slack function is guaranteed to be within the bounds.

**Comment by endrebak** [comment]
Thanks for the suggestion. The function
https://github.com/biocore-ntnu/pyranges/blob/master/pyranges/genomicfeatures/genomicfeatures.py#L27

does this.

So you can first call slack, then `pr.gf.genome_bounds`. I think it should
solve your problem, but please tell me if it does not :)
